del /s    *.hdb  
del /s    *.cdb  
del /s    *.tdf  
del /s    *.ddb  
del /s    *.qmsg  
del /s    *.hsd  
del /s    *.rdb  
del /s    *.ammdb  
del /s    *.bpm  
del /s    *.tdb  
del /s    *.hier_info  
del /s    *.db_info  
del /s    *.hif  
del /s    *.idb  
del /s    *.ipinfo  
del /s    *.kpt  
del /s    *.logdb  
del /s    *.sci  
del /s    *.syn_hier_info  
del /s    *.xml  
del /s    *.rpt  
del /s    *.wlf  
del /s    *.sdo  
del /s    *.vo  
del /s    *.xrf         
del /s    *.dbs  
del /s    *.psm  
del /s    *.qws  
del /s    *.sft     
del /s    *.qws  
del /s    *.sft         
del /s    *.qws  
del /s    *.sft         
del /s    *.qws  
del /s    *.sft         
del /s    JLinkLog.txt  
del /s    *.iex  
del /s    *.htm  
del /s    *.sct  
del /s    *.map  
del /s    *.bak  